discord:
  botToken: -----------------------RESOURCE-------------------------------------
  serverId: "276931890735218689"
  channels:
    {
      welcomeChanelId: "925583159964352643",
      adminChanelId: "927283856053252106",
      whitelistChanelId: "927283856053252106",
      botLogChannelId: "927283856053252106",
      javaLogChannelId: "927283856053252106",
    }
  roles:
    {
      discordAdminRoleId: "293133215500075010",
      moderatorRoleId: "1021054284214833182",
      devRoleId: "1021054460438523976",
      helperRoleId: "1021054460438523976",
    }
database:
  {
    type: mysql,
    host: localhost,
    port: "3306",
    name: whitelist_dmc,
    user: whitelist_dmc,
    password: mysql,
    defaultTable: wje_users,
    maxConnection: "15",
    maxIdleConnection: "5",
  }
minecraft:
  {
    portJava: "25565",
    portBedrock: "19132",
    javaIp: rvdprojects.synology.me,
    bedrockIp: rvdprojects.synology.me,
  }
features: { maxHoursFor2FA: "24", showAllWorldsMeteo: "true", defaultLang: FR }
httpServer:
  {
    appRoot: "app",
    appName: "WDMC-Spark",
    keyStoreFile: "keystore.jks",
    keyStorePassword: "password"
  }
linksCommands:
  linkOne:
    {
      useDiscord: true,
      useMinecraft: true,
      isPublicMsg: true,
      permission: everyone,
      aliasTradKey: CUSTOM_LINK_LINK1_ALIAS,
      descriptionTradKey: CUSTOM_LINK_LINK1_ALIAS,
      linkTradKey: CUSTOM_LINK_LINK1_LINK,
      minecraftTextTradKey: CUSTOM_LINK_LINK1_TXT_MC,
      discordTextTradKey: CUSTOM_LINK_LINK1_TXT_DISC,
    }
  linkTwo:
    {
      useDiscord: true,
      useMinecraft: false,
      isPublicMsg: false,
      permission: everyone,
      aliasTradKey: CUSTOM_LINK_LINK2_ALIAS,
      descriptionTradKey: CUSTOM_LINK_LINK2_ALIAS,
      linkTradKey: CUSTOM_LINK_LINK2_LINK,
      minecraftTextTradKey: CUSTOM_LINK_LINK2_TXT_MC,
      discordTextTradKey: CUSTOM_LINK_LINK2_TXT_DISC,
    }
  linkThree:
    {
      useDiscord: false,
      useMinecraft: true,
      isPublicMsg: false,
      permission: everyone,
      aliasTradKey: CUSTOM_LINK_LINK3_ALIAS,
      descriptionTradKey: CUSTOM_LINK_LINK3_DESC,
      linkTradKey: CUSTOM_LINK_LINK3_LINK,
      minecraftTextTradKey: CUSTOM_LINK_LINK3_TXT_MC,
      discordTextTradKey: CUSTOM_LINK_LINK3_TXT_DISC,
    }
misc:
  {
    confirmLinkCmdName: w-link,
    minecraftInfosLink: "https://www.spigotmc.org/resources/whitelist-dmc.111065/",
    serverContactEmail: webdevteam@rvdprojects.com,
  }
