name: WhitelistDMC
version: '${project.version}'
main: main.WhitelistDMC
api-version: 1.15
author: Izocel
commands:
   w-link:
      description: Used to authenticate your Discord and Minecraft accounts.
      usage: /<w-link-command>
