name: WhitelistDmc
version: '${project.version}'
main: main.WhitelistDmc
api-version: 1.15
author: Izocel
commands:
   w-link:
      description: Used to authenticate your Discord and Minecraft accounts.
      usage: /<w-link-command>
   w-hyperlinks:
      description: Used to send dynamic hyperlinks.
      usage: /<w-hyperlinks-command>
   test-econ:
      description: Used to test vault economy.
      usage: /test-econ
