name: WhitelistJe
version: '${project.version}'
main: main.WhitelistJe
api-version: 1.15
author: Izocel
commands:
   wje-link:
      description: Pour confirmer le lien entre votre compte Minecraft et votre Discord.
      usage: /<wje-link-command>
