api: "1.15"
name: WhitelistDmcNode
version: '${project.version}'
main: main.WhitelistDmcNode
api-version: 1.15
author: Izocel
softdepends: [Citizens]
commands:
   w-link:
      description: Used to authenticate your Discord and Minecraft accounts.
      usage: /<w-link-command>
   w-hyperlinks:
      description: Used to send dynamic hyperlinks.
      usage: /<w-hyperlinks-command>
   w-test:
      description: Used to test in 'dev' mode
      usage: /w-test
