name: WhitelistJe
version: '${project.version}'
main: main.WhitelistJe
api-version: 1.15
author: Izocel
commands:
   wje-link:
      description: This is a demo command.
      usage: /<wje-link-command>
